[project]
name = "tweet-youtube-stream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client>=2.159.0",
    "pyyaml>=6.0.2",
    "tweepy>=4.15.0",
]
